### ISSUE TITLE
Training time？

### ISSUE THREAD

**Issue by visionxyz** [gjy3035/GCC-SFCN#3]
Can I know how much time will it take to train the SOTA？ Thanks！

**Comment by gjy3035** [comment]
For the UCF-QNRF, we train ~400 epoches for SFCN+ on single 1080Ti, which takes about 25 hours. The training time may be more than the theoretical cost, because we conduct other experiments on the same machine (low CPU usage slows down the speed of the dataloader).

In order to obtain pretrained GCC model, we implemet the experiment on four 1080Ti, which takes ~38 hours (100 epoches).

Due to the different data volumes and characteristics, the experiments on different datasets may take different times.
